

mt_genes_info = {
    "P00395": {
        "protein": "Cytochrome c oxidase subunit 1",
        "gene": "MT-CO1",
        "amino_acids": 'MFADRWLFSTNHKDIGTLYLLFGAWAGVLGTALSLLIRAELGQPGNLLGNDHIYNVIVTAHAFVMIFFMVMPIMIGGFGNWLVPLMIGAPDMAFPRMNNMSFWLLPPSLLLLLASAMVEAGAGTGWTVYPPLAGNYSHPGASVDLTIFSLHLAGVSSILGAINFITTIINMKPPAMTQYQTPLFVWSVLITAVLLLLSLPVLAAGITMLLTDRNLNTTFFDPAGGGDPILYQHLFWFFGHPEVYILILPGFGMISHIVTYYSGKKEPFGYMGMVWAMMSIGFLGFIVWAHHMFTVGMDVDTRAYFTSATMIIAIPTGVKVFSWLATLHGSNMKWSAAVLWALGFIFLFTVGGLTGIVLANSSLDIVLHDTYYVVAHFHYVLSMGAVFAIMGGFIHWFPLFSGYTLDQTYAKIHFTIMFIGVNLTFFPQHFLGLSGMPRRYSDYPDAYTTWNILSSVGSFISLTAVMLMIFMIWEAFASKRKVLMVEEPSMNLEWLYGCPPPYHTFEEPVYMKS'
    },
    "P00403": {
        "protein": "Cytochrome c oxidase subunit 2",
        "gene": "MT-CO2",
        "amino_acids": 'MAHAAQVGLQDATSPIMEELITFHDHALMIIFLICFLVLYALFLTLTTKLTNTNISDAQEMETVWTILPAIILVLIALPSLRILYMTDEVNDPSLTIKSIGHQWYWTYEYTDYGGLIFNSYMLPPLFLEPGDLRLLDVDNRVVLPIEAPIRMMITSQDVLHSWAVPTLGLKTDAIPGRLNQTTFTATRPGVYYGQCSEICGANHSFMPIVLELIPLKIFEMGPVFTL'
    },
    "P00414": {
        "protein": "Cytochrome c oxidase subunit 3",
        "gene": "MT-CO3",
        "amino_acids": 'MTHQSHAYHMVKPSPWPLTGALSALLMTSGLAMWFHFHSMTLLMLGLLTNTLTMYQWWRDVTRESTYQGHHTPPVQKGLRYGMILFITSEVFFFAGFFWAFYHSSLAPTPQLGGHWPPTGITPLNPLEVPLLNTSVLLASGVSITWAHHSLMENNRNQMIQALLITILLGLYFTLLQASEYFESPFTISDGIYGSTFFVATGFHGLHVIIGSTFLTICFIRQLMFHFTSKHHFGFEAAAWYWHFVDVVWLFLYVSIYWWGS'
    },
    "P00846": {
        "protein": "ATP synthase subunit a",
        "gene": "MT-ATP6",
        "amino_acids": 'MNENLFASFIAPTILGLPAAVLIILFPPLLIPTSKYLINNRLITTQQWLIKLTSKQMMTMHNTKGRTWSLMLVSLIIFIATTNLLGLLPHSFTPTTQLSMNLAMAIPLWAGTVIMGFRSKIKNALAHFLPQGTPTPLIPMLVIIETISLLIQPMALAVRLTANITAGHLLMHLIGSATLAMSTINLPSTLIIFTILILLTILEIAVALIQAYVFTLLVSLYLHDNT'
    },
    "P03928": {
        "protein": "ATP synthase protein 8",
        "gene": "MT-ATP8",
        "amino_acids": 'MPQLNTTVWPTMITPMLLTLFLITQLKMLNTNYHLPPSPKPMKMKNYNKPWEPKWTKICSLHSLPPQS'
    },
    "P03886": {
        "protein": "NADH-ubiquinone oxidoreductase chain 1",
        "gene": "MT-ND1",
        "amino_acids": 'MPMANLLLLIVPILIAMAFLMLTERKILGYMQLRKGPNVVGPYGLLQPFADAMKLFTKEPLKPATSTITLYITAPTLALTIALLLWTPLPMPNPLVNLNLGLLFILATSSLAVYSILWSGWASNSNYALIGALRAVAQTISYEVTLAIILLSTLLMSGSFNLSTLITTQEHLWLLLPSWPLAMMWFISTLAETNRTPFDLAEGESELVSGFNIEYAAGPFALFFMAEYTNIIMMNTLTTTIFLGTTYDALSPELYTTYFVTKTLLLTSLFLWIRTAYPRFRYDQLMHLLWKNFLPLTLALLMWYVSMPITISSIPPQT'
        
    },
    "P03891": {
        "protein": "NADH-ubiquinone oxidoreductase chain 2",
        "gene": "MT-ND2",
        "amino_acids": 'MNPLAQPVIYSTIFAGTLITALSSHWFFTWVGLEMNMLAFIPVLTKKMNPRSTEAAIKYFLTQATASMILLMAILFNNMLSGQWTMTNTTNQYSSLMIMMAMAMKLGMAPFHFWVPEVTQGTPLTSGLLLLTWQKLAPISIMYQISPSLNVSLLLTLSILSIMAGSWGGLNQTQLRKILAYSSITHMGWMMAVLPYNPNMTILNLTIYIILTTTAFLLLNLNSSTTTLLLSRTWNKLTWLTPLIPSTLLSLGGLPPLTGFLPKWAIIEEFTKNNSLIIPTIMATITLLNLYFYLRLIYSTSITLLPMSNNVKMKWQFEHTKPTPFLPTLIALTTLLLPISPFMLMIL'
    },
    "P03897": {
        "protein": "NADH-ubiquinone oxidoreductase chain 3",
        "gene": "MT-ND3",
        "amino_acids": 'MNFALILMINTLLALLLMIITFWLPQLNGYMEKSTPYECGFDPMSPARVPFSMKFFLVAITFLLFDLEIALLLPLPWALQTTNLPLMVMSSLLLIIILALSLAYEWLQKGLDWTE'
    },
    "P03905": {
        "protein": "NADH-ubiquinone oxidoreductase chain 4",
        "gene": "MT-ND4",
        "amino_acids": 'MLKLIVPTIMLLPLTWLSKKHMIWINTTTHSLIISIIPLLFFNQINNNLFSCSPTFSSDPLTTPLLMLTTWLLPLTIMASQRHLSSEPLSRKKLYLSMLISLQISLIMTFTATELIMFYIFFETTLIPTLAIITRWGNQPERLNAGTYFLFYTLVGSLPLLIALIYTHNTLGSLNILLLTLTAQELSNSWANNLMWLAYTMAFMVKMPLYGLHLWLPKAHVEAPIAGSMVLAAVLLKLGGYGMMRLTLILNPLTKHMAYPFLVLSLWGMIMTSSICLRQTDLKSLIAYSSISHMALVVTAILIQTPWSFTGAVILMIAHGLTSSLLFCLANSNYERTHSRIMILSQGLQTLLPLMAFWWLLASLANLALPPTINLLGELSVLVTTFSWSNITLLLTGLNMLVTALYSLYMFTTTQWGSLTHHINNMKPSFTRENTLMFMHLSPILLLSLNPDIITGFSS'
    },
    "P03915": {
        "protein": "NADH-ubiquinone oxidoreductase chain 5",
        "gene": "MT-ND5",
        "amino_acids": 'MTMHTTMTTLTLTSLIPPILTTLVNPNKKNSYPHYVKSIVASTFIISLFPTTMFMCLDQEVIISNWHWATTQTTQLSLSFKLDYFSMMFIPVALFVTWSIMEFSLWYMNSDPNINQFFKYLLIFLITMLILVTANNLFQLFIGWEGVGIMSFLLISWWYARADANTAAIQAILYNRIGDIGFILALAWFILHSNSWDPQQMALLNANPSLTPLLGLLLAAAGKSAQLGLHPWLPSAMEGPTPVSALLHSSTMVVAGIFLLIRFHPLAENSPLIQTLTLCLGAITTLFAAVCALTQNDIKKIVAFSTSSQLGLMMVTIGINQPHLAFLHICTHAFFKAMLFMCSGSIIHNLNNEQDIRKMGGLLKTMPLTSTSLTIGSLALAGMPFLTGFYSKDHIIETANMSYTNAWALSITLIATSLTSAYSTRMILLTLTGQPRFPTLTNINENNPTLLNPIKRLAAGSLFAGFLITNNISPASPFQTTIPLYLKLTALAVTFLGLLTALDLNYLTNKLKMKSPLCTFYFSNMLGFYPSITHRTIPYLGLLTSQNLPLLLLDLTWLEKLLPKTISQHQISTSIITSTQKGMIKLYFLSFFFPLILTLLLIT'
    },
    "P03923": {
        "protein": "NADH-ubiquinone oxidoreductase chain 6",
        "gene": "MT-ND6",
        "amino_acids": 'MMYALFLLSVGLVMGFVGFSSKPSPIYGGLVLIVSGVVGCVIILNFGGGYMGLMVFLIYLGGMMVVFGYTTAMAIEEYPEAWGSGVEVLVSVLVGLAMEVGLVLWVKEYDGVVVVVNFNSVGSWMIYEGEGSGLIREDPIGAGALYDYGRWLVVVTGWTLFVGVYIVIEIARGN'
    },
    "P03901": {
        "protein": "NADH-ubiquinone oxidoreductase chain 4L",
        "gene": "MT-ND4L",
        "amino_acids": 'MPLIYMNIMLAFTISLLGMLVYRSHLMSSLLCLEGMMLSLFIMATLMTLNTHSLLANIVPIAMLVFAACEAAVGLALLVSISNTYGLDYVHNLNLLQC'
    },
    "P00156": {
        "protein": "Cytochrome b",
        "gene": "MT-CYB",
        "amino_acids": 'MTPMRKTNPLMKLINHSFIDLPTPSNISAWWNFGSLLGACLILQITTGLFLAMHYSPDASTAFSSIAHITRDVNYGWIIRYLHANGASMFFICLFLHIGRGLYYGSFLYSETWNIGIILLLATMATAFMGYVLPWGQMSFWGATVITNLLSAIPYIGTDLVQWIWGGYSVDSPTLTRFFTFHFILPFIIAALATLHLLFLHETGSNNPLGITSHSDKITFHPYYTIKDALGLLLFLLSLMTLTLFSPDLLGDPDNYTLANPLNTPPHIKPEWYFLFAYTILRSVPNKLGGVLALLLSILILAMIPILHMSKQQSMMFRPLSQSLYWLLAADLLILTWIGGQPVSYPFTIIGQVASVLYFTTILILMPTISLIENKMLKWA'
    },
    "Q8IVG9": {
    "protein": "Humanin",
    "gene": "MT-RNR2",
    "amino_acids": 'MAPRGFSCLLLLTSEIDLPVKRRA'
}
}

class Gene:

    def __init__(self, symbol, startPos, endPos):
        self.symbol = symbol
        self.startPos = int(startPos)
        self.endPos = int(endPos)

geneList = [
    Gene('MT-TF', '577', '647'),
    Gene('MT-RNR1', '648', '1601'),
    Gene('MT-TV', '1602', '1670'),
    Gene('MT-RNR2', '1671', '3229'),
    Gene('MT-TL1', '3230', '3304'),
    Gene('MT-ND1', '3307', '4262'),
    Gene('MT-TI', '4263', '4331'),
    Gene('MT-TQ', '4329', '4400'),
    Gene('MT-TM', '4402', '4469'),
    Gene('MT-ND2', '4470', '5511'),
    Gene('MT-TW', '5512', '5579'),
    Gene('MT-TA', '5587', '5655'),
    Gene('MT-TN', '5657', '5729'),
    Gene('MT-TC', '5761', '5826'),
    Gene('MT-TY', '5826', '5891'),
    Gene('MT-CO1', '5904', '7445'),
    Gene('MT-TS1', '7446', '7514'),
    Gene('MT-TD', '7518', '7585'),
    Gene('MT-CO2', '7586', '8269'),
    Gene('MT-TK', '8295', '8364'),
    Gene('MT-ATP8', '8366', '8572'),
    Gene('MT-ATP6', '8527', '9207'),
    Gene('MT-CO3', '9207', '9990'),
    Gene('MT-TG', '9991', '10058'),
    Gene('MT-ND3', '10059', '10404'),
    Gene('MT-TR', '10405', '10469'),
    Gene('MT-ND4L', '10470', '10766'),
    Gene('MT-ND4', '10760', '12137'),
    Gene('MT-TH', '12138', '12206'),
    Gene('MT-TS2', '12207', '12265'),
    Gene('MT-TL2', '12266', '12336'),
    Gene('MT-ND5', '12337', '14148'),
    Gene('MT-ND6', '14149', '14673'),
    Gene('MT-TE', '14674', '14742'),
    Gene('MT-CYB', '14747', '15887'),
    Gene('MT-TT', '15888', '15953'),
    Gene('MT-TP', '15956', '16023'),
    Gene('MT-MOTS-c','1343','1393'),
    Gene('MT-SHLP1','2490','2561'),
    Gene('MT-SHLP2','2092','2170'),
    Gene('MT-SHLP3','1707','1821'),
    Gene('MT-SHLP4','2446','2524'),
    Gene('MT-SHLP5','2785','2856'),
    Gene('MT-SHLP6','2992','3051'),
    Gene('MT-HUMANIN','2634','2707'),]   



